window.pageTranslations = {
    es: {
        'bio.p1': 'Diego de Aduriz estudió Bellas Artes en la Escuela Nacional de Bellas Artes Prilidiano Pueyrredón y Arquitectura en la Universidad Nacional de Rosario. Participó en la Beca Kuitca (2003), CIA (2009) y en el Laboratorio de Acción, en el Centro Cultural San Martin (2019).',
        'bio.p2': 'Trabaja de manera aleatoria en dibujo, pintura, mural, collage, diseño de moda, máscaras, performances, lectura de poesía, autoedicion de libritos y fanzines y publicaciones online. Realizó muestras y desfiles en galerías y museos de la Argentina y el exterior: MALBA, arteBA, Buenos Aires Fashion Week, Frieze Art Fair en Londres, Consulado Argentino en New York, Hogar Collection Gallery en Brooklyn, Centro Cultural Renato Russo en Brasilia, Semana Internacional de la Moda de Madrid, Belleza y Felicidad, Appetite, Miau Miau, Mite, Gabelich Contemporáneo en Rosario, CCBorges, CCRecoleta, Museo de Arte Contemporáneo de Mendoza, Museo de Arte Contemporáneo de Salta, entre otros.',
        'bio.p3': 'Participó en los siguientes premios y salones: Premio Nacional de Pintura Banco Nación (2010), Premio Andreani (2015, 2017), Salón Nacional de Rosario (2019), XXIV PREMIO KLEMM (2020), Premio de Pintura del Banco Central (2020). En el año 2021 fue seleccionado para el Salón Nacional de Artes Visuales. En 2020 realizó un “Tutorial de Máscaras “, video-performance para el Museo de Arte Moderno, una charla y performance para el Palais de Glace (“Yo seré tu espejo”) y “La fortuna del Diablo”, performance online con el auspicio del Instituto Nacional del Teatro.',
        'bio.p4': 'Desde Diciembre de 2020 es representado por la galería Aldo de Sousa, donde en marzo del 2021 presentó la muestra “MI CUERPO ELÉCTRICO”. Publicó el libro <b>HOY RECORDÉ ALGO QUE HABÍA OLVIDADO</b> (Ivan Rosado , 2017), <b>UN BESO EN LA CASA DE LOS SUEÑOS</b> (Triana, 2021), y las plaquetas <b>TRES SEXOS</b> (Belleza y Felicidad, 2014) y <b>METRÓNOMO</b> (Spyral Jetti, 2015).',
        'bio.contact_me': 'Contact Me'
    },
    en: {
        'bio.p1': 'Diego de Aduriz studied Fine Arts at the Prilidiano Pueyrredón National School of Fine Arts and Architecture at the National University of Rosario. He participated in the Kuitca Scholarship (2003), CIA (2009), and the Action Laboratory at the San Martin Cultural Center (2019).',
        'bio.p2': 'He works randomly in drawing, painting, muralism, collage, fashion design, masks, performances, poetry reading, self-publishing of booklets and fanzines, and online publications. He has held exhibitions and fashion shows in galleries and museums in Argentina and abroad: MALBA, arteBA, Buenos Aires Fashion Week, Frieze Art Fair in London, Argentine Consulate in New York, Hogar Collection Gallery in Brooklyn, Renato Russo Cultural Center in Brasilia, Madrid International Fashion Week, Belleza y Felicidad, Appetite, Miau Miau, Mite, Gabelich Contemporáneo in Rosario, CCBorges, CCRecoleta, Museum of Contemporary Art of Mendoza, Museum of Contemporary Art of Salta, among others.',
        'bio.p3': 'He participated in the following awards and salons: Banco Nación National Painting Prize (2010), Andreani Prize (2015, 2017), Rosario National Salon (2019), XXIV KLEMM PRIZE (2020), Central Bank Painting Prize (2020). In 2021, he was selected for the National Salon of Visual Arts. In 2020, he created a “Mask Tutorial,” a video-performance for the Museum of Modern Art, a talk and performance for the Palais de Glace (“I’ll Be Your Mirror”), and “The Devil’s Fortune,” an online performance sponsored by the National Theater Institute.',
        'bio.p4': 'Since December 2020, he has been represented by the Aldo de Sousa gallery, where in March 2021 he presented the exhibition “MY ELECTRIC BODY.” He published the book <b>TODAY I REMEMBERED SOMETHING I HAD FORGOTTEN</b> (Ivan Rosado, 2017), <b>A KISS IN THE HOUSE OF DREAMS</b> (Triana, 2021), and the chapbooks <b>THREE SEXES</b> (Belleza y Felicidad, 2014) and <b>METRONOME</b> (Spyral Jetti, 2015).',
        'bio.contact_me': 'Contact Me'
    }
};
