window.products = [
    {
        "id": "catastrofe-catarsis",
        "title": "Catástrofe / Catarsis",
        "description": "<strong>54 × 50 cm</strong> de <strong>acrílico sobre tela</strong>. Una obra donde De Aduriz organiza signos, palabras e imágenes en un sistema visual de gran intensidad simbólica. La composición, precisa y frontal, articula tensión entre caos y transformación, con una iconografía propia que mezcla escritura, emblema y visión. <strong>Pieza única</strong>, firmada. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "54 x 50 cm",
        "technique": "Acrílico sobre tela",
        "category": "simbolico",
        "image": "/portfolio/sections/obras/catastrofe-catarsis-54x50-pastel-tiza-sobre-telas.jpeg",
        "sold": false,
        "year": "a confirmar"
    },
    {
        "id": "fama-fortuna-fake-news",
        "title": "Fama / Fortuna / Fake News",
        "description": "<strong>52 × 52 cm</strong>. En esta pieza, De Aduriz cruza lenguaje, símbolo y crítica contemporánea en una superficie de alto impacto visual. La obra combina humor, tensión gráfica y referencias al dinero, la circulación de imágenes y la distorsión de lo real. <strong>Pieza única</strong>, firmada DDA 2020. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "52 x 52 cm",
        "technique": "Acrílico sobre tela",
        "category": "simbolico",
        "image": "/portfolio/sections/obras/fama-fortuna-fake-news-52x52.jpeg",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "no-me-veras-llorar-siete-gotitas-negras",
        "title": "No me verás llorar / Siete gotitas negras",
        "description": "<strong>52 × 52 cm</strong>. Una obra de composición austera y gran potencia poética, donde texto y símbolo construyen una imagen directa, casi ritual. De Aduriz trabaja aquí con una economía formal que refuerza el clima de advertencia, ironía y condensación emocional. <strong>Pieza única</strong>, firmada y fechada 7-1-20. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "52 x 52 cm",
        "technique": "Acrílico sobre tela",
        "category": "texto",
        "image": "/portfolio/sections/obras/no-me-veras-llorar-siete-gotitas-negras-52x52.jpeg",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "supervision-superhabit",
        "title": "Supervisión / Superhabit",
        "description": "<strong>54 × 50 cm</strong> de <strong>acrílico sobre tela</strong> (<strong>2020</strong>). Una pieza donde escritura, diagrama y símbolo se integran en una estructura visual rigurosa y enigmática. Aduriz despliega un lenguaje propio, entre lo místico, lo gráfico y lo conceptual, con una presencia visual clara y singular. <strong>Pieza única</strong>, firmada DDA 2020. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "54 x 50 cm",
        "technique": "Acrílico sobre tela",
        "category": "simbolico",
        "image": "/portfolio/sections/obras/supervision-superhabit-54x50-pastel-tiza-sobre-telas.jpeg",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "escriturismo-para-los-dias-de-calor",
        "title": "Escriturismo para los días de calor",
        "description": "<strong>57 × 37 cm</strong> de <strong>óleo sobre puerta de madera</strong> (<strong>2024</strong>). Una pieza donde la palabra se vuelve imagen, ritmo y desvío. De Aduriz trabaja sobre una puerta intervenida como si fuera un umbral entre escritura, humor y pintura. Las asociaciones verbales y los cruces de sentido construyen una obra de fuerte identidad visual, entre la poesía gráfica y el objeto. <strong>Pieza única</strong>, firmada DDA 2024. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "57 x 37 cm",
        "technique": "Óleo sobre puerta de madera",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/escriturismo-para los-dias-de-calor-57x37-oleo-sobre-puerta-de-madera.jpg",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "estiercol-en-grageas-por-si-las-moscas",
        "title": "Estiércol en grageas (por si las moscas)",
        "description": "<strong>57 × 37 cm</strong> de <strong>óleo sobre puerta de madera</strong>. En esta obra, De Aduriz vuelve a usar la palabra como materia visual y crítica. Sobre una puerta pintada en turquesa, despliega pares, equívocos y asociaciones que mezclan ironía, cultura popular y tensión conceptual. El resultado es una pieza singular, directa y cargada de humor. <strong>Pieza única</strong>, firmada. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "57 x 37 cm",
        "technique": "Óleo sobre puerta de madera",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/estiercol-en-grageas-57x37-oleo-sobre-puerta-de-madera.jpg",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "paisaje-con-angel-verde-fumando-dos-gatos-y-aliento-divino",
        "title": "Paisaje con ángel verde fumando, dos gatos y aliento divino",
        "description": "<strong>51 × 26 cm</strong> de <strong>marcadores y lápiz sobre papel</strong>. Un paisaje horizontal que despliega un universo completo: dos gatos — uno marrón grande con ojos de distintos colores a la izquierda, otro azul etéreo flotando en el centro —, un ángel verde fumando en el medio campo, una arquitectura gótica naranja, un arcoiris denso y matérico, una bailarina blanca y negra, y un pino verde al fondo derecho. Todo convive sin jerarquía, como si el papel fuera un territorio donde cualquier cosa puede existir junto a cualquier otra. El reverso de la obra también está intervenido: una nube con el título escrito a mano, dos ojos y un pequeño gato dormido — un segundo cuadro dentro del mismo soporte. <strong>Pieza única</strong>, con reverso intervenido. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "51 x 26 cm",
        "technique": "Marcadores y lápiz sobre papel",
        "category": "paisaje",
        "image": "/portfolio/sections/obras/paisaje-con-angel-verde-fumando-dos-gatos-y-aliento-divino-51x26.jpeg",
        "images": [
            "/portfolio/sections/obras/paisaje-con-angel-verde-fumando-dos-gatos-y-aliento-divino-51x26.jpeg",
            "/portfolio/sections/obras/paisaje-con-angel-verde-fumando-dos-gatos-y-aliento-divino-51x26-reverso.jpeg"
        ],
        "sold": false,
        "year": "2021"
    },
    {
        "id": "pax-aeterna",
        "title": "Pax æterna",
        "description": "<strong>50 × 36 cm</strong> de <strong>marcadores blancos sobre papel negro</strong> (<strong>2021</strong>). Fechada el 30 de diciembre de 2021, firmada DDA. Una figura central — mezcla de payaso, robot y ser ceremonial — proclama PAX desde un globo de diálogo. El fondo negro actúa como cielo nocturno o pizarrón: la línea blanca brilla con la misma energía que tiene un trazo hecho de una sola vez, sin correcciones. A su alrededor, símbolos personales del artista: una estrella de cinco puntas, un triángulo con ojo, signos que parecen jeroglíficos propios, una escalera. Una obra íntima y festiva al mismo tiempo — hecha en los últimos días del año, con la calma y la precisión que solo aparece cuando se está muy seguro de lo que se hace. <strong>Pieza única</strong>, firmada y fechada. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "50 x 36 cm",
        "technique": "Marcadores sobre papel",
        "category": "obras",
        "image": "/portfolio/sections/obras/Pax-æterna-50x36-2021.jpeg",
        "sold": false,
        "year": "2021"
    },
    {
        "id": "convivencia-pacifica-marcadores",
        "title": "Convivencia pacífica (marcadores)",
        "description": "<strong>50 × 34 cm</strong> de <strong>marcadores sobre papel</strong>. Un papel que no tiene miedo al vacío: cada centímetro está habitado por alguna criatura, planta, símbolo o pequeño acontecimiento. Gnomo, cactus, diamante, gato alado, robot, casas, serpiente — todos conviven sin jerarquía y sin conflicto. Una obra de esas que cuanto más tiempo la mirás, más cosas encontrás. Ideal para un estudio, una habitación infantil o cualquier espacio que necesite energía y humor. <strong>Pieza única</strong>, firmada. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "50 x 34 cm",
        "technique": "Marcadores sobre papel",
        "category": "ilustraciones",
        "image": "/portfolio/sections/obras/convivencia-pacifica-marcadores-sobre-papel.png",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "naturaleza-artistica-con-lapiz-y-montana",
        "title": "Naturaleza artística con lápiz y montaña",
        "description": "<strong>50 × 34 cm</strong> de <strong>lápiz y marcadores sobre papel</strong>. En primer plano una montaña o criatura marrón enorme, sonriente, cubierta de flores — con un diamante morado en la cabeza. A su lado, una figura amarilla más delicada. Atrás, una cinta roja que recorre todo el plano, un ángel fumando, un fantasma, casas, árboles con cara. La mezcla de lápiz y marcador crea capas de densidad diferentes: lo construido a mano convive con lo gestual. Una obra de esas que tienen su propia lógica interna. <strong>Pieza única</strong>, firmada. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "50 x 34 cm",
        "technique": "Lápiz y marcadores sobre papel",
        "category": "ilustraciones",
        "image": "/portfolio/sections/obras/naturaleza-artistica-con-lapiz-y-montaña-lapiz-sobre-papel.png",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "paisaje-con-dialogo-misterioso",
        "title": "Paisaje con diálogo misterioso",
        "description": "<strong>50 × 34 cm</strong> de <strong>marcadores sobre papel</strong>. Un paisaje que mezcla lo doméstico con lo inexplicable: casas rosadas, un arcoiris, montañas verdes, olas azules — y en el medio, escrita a mano con flecha, la palabra <em>clarovidencia</em>. En el ángulo superior derecho, un objeto volador no identificado. El diálogo del título no está en ningún globo de texto — está entre los elementos, en la tensión entre lo cotidiano y lo extraño. <strong>Pieza única</strong>, firmada. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "50 x 34 cm",
        "technique": "Marcadores sobre papel",
        "category": "paisajes",
        "image": "/portfolio/sections/obras/paisaje-con-dialogo-misterioso-marcadores-sobre-papel.png",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "paisaje-regio-lapiz-marcadores",
        "title": "Paisaje regio",
        "description": "<strong>50 × 34 cm</strong> de <strong>lápiz y marcadores sobre papel</strong> (<strong>2020</strong>). Composición vertical, firmada DDA 2020. Un pájaro rojo grande con ojo ocupa el centro — mitad criatura, mitad forma abstracta. A la izquierda, un robot o marioneta dibujado en violeta con articulaciones visibles. Abajo, un pequeño pueblo volcánico y la inscripción 칸누 en coreano. Una obra que cruza culturas y registros sin esfuerzo, con la soltura que solo da años de dibujo. <strong>Pieza única</strong>, firmada. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "50 x 34 cm",
        "technique": "Lápiz y marcadores sobre papel",
        "category": "paisajes",
        "image": "/portfolio/sections/obras/paisaje-regio-lapiz-marcadores-sobre-papel.png",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "autorretrato-con-moño",
        "title": "Autorretrato con moño",
        "description": "<strong>82 × 56 cm</strong> de <strong>pastel al óleo sobre madera</strong> (<strong>2025</strong>). El moño como gesto: un accesorio que en manos de De Aduriz se convierte en declaración de identidad. Este autorretrato reciente continúa la serie de autorretratos del artista con una presencia directa y desafiante — la mirada al frente, el adorno como escudo y comme performance. El <strong>pastel al óleo sobre madera</strong> aporta una textura densa y luminosa que el lienzo no permitiría. <strong>Obra nueva</strong>, disponible con <strong>certificado de autenticidad</strong>.",
        "price": "Consultar",
        "dimensions": "82 x 56 cm",
        "technique": "Pastel al óleo sobre madera",
        "category": "Autorretratos",
        "image": "/portfolio/sections/obras/autorretrato-con-moño-2025-82x56.png",
        "sold": false,
        "year": "2025"
    },
    {
        "id": "gato-blanco-nuevo",
        "title": "Gato Blanco Nuevo",
        "description": "<strong>69 × 59 cm</strong> de <strong>pastel al óleo sobre puerta de chapa</strong> (<strong>2025</strong>). Un gato blanco sobre una puerta de chapa intervenida — el soporte industrial en tensión con la delicadeza del animal. El blanco aquí no es ausencia sino todo lo contrario: densidad, luz propia, presencia que domina el espacio. Una de las piezas más recientes del artista, donde el objeto cotidiano (la puerta) se convierte en campo pictórico. <strong>Pieza única</strong> con <strong>certificado de autenticidad</strong>.",
        "price": "Consultar",
        "dimensions": "69 x 59 cm",
        "technique": "Pastel al óleo sobre puerta de chapa",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/Gato-Blanco-Nuevo-2025-69x59.png",
        "sold": false,
        "year": "2025"
    },
    {
        "id": "gato-11-11",
        "title": "Gato 11:11",
        "description": "<strong>69 × 30 cm</strong> de <strong>pastel al óleo sobre madera</strong> (<strong>2025</strong>). El 11:11 es el momento del deseo, el instante en que el tiempo se duplica y se abre una ventana. Un gato en ese umbral: mitad aquí, mitad en otra dimensión. El formato vertical y angosto de la obra refuerza esa sensación de portal, de pasaje. Una pieza cargada de sincronías para quienes creen en ellas — y de belleza pura para quienes no. Disponible con <strong>certificado de autenticidad</strong>.",
        "price": "Consultar",
        "dimensions": "69 x 30 cm",
        "technique": "Pastel al óleo sobre madera",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/gato-11-11-2025-69x30.png",
        "sold": false,
        "year": "2025"
    },
    {
        "id": "convivencia-pacifica",
        "title": "Convivencia pacífica",
        "description": "<strong>40 × 30 cm</strong> de <strong>pastel al óleo sobre tela</strong> (<strong>2024</strong>). En el universo de Aduriz conviven figuras que en otra parte serían incompatibles: lo humano y lo animal, lo cósmico y lo doméstico, el humor y la profundidad. Esta obra lo condensa en un formato íntimo — <strong>40 × 30 cm</strong> que caben en cualquier espacio pero que generan una conversación silenciosa con quien los habita. Ideal como primera obra o como pieza de una colección en crecimiento. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "40 x 30 cm",
        "technique": "Pastel al óleo sobre tela",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/convivencia-pacifica-2024-40x30.png",
        "sold": false,
        "year": "2024"
    },
    {
        "id": "gato-alfa-omega",
        "title": "Gato Alfa & Omega",
        "description": "<strong>60 × 40 cm</strong> de <strong>pastel al óleo sobre chapa</strong> (<strong>2025</strong>). El principio y el fin en un mismo animal. El gato como figura que contiene todas las posibilidades — el alfa que abre y el omega que cierra. La chapa como soporte le da a esta obra una materialidad cruda y contemporánea que contrasta con la suavidad del pastel al óleo. Una pieza que funciona igual en un espacio doméstico que en uno institucional. <strong>Obra nueva</strong> 2025, con <strong>certificado de autenticidad</strong>.",
        "price": "Consultar",
        "dimensions": "60 x 40 cm",
        "technique": "Pastel al óleo sobre chapa",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/gato-alfa-&-omega-2025-60x40.png",
        "sold": false,
        "year": "2025"
    },
    {
        "id": "pitufex",
        "title": "Pitufex",
        "description": "<strong>46 × 36 cm</strong> de <strong>pastel al óleo sobre puerta de madera</strong> pequeña (<strong>2025</strong>). El nombre es un invento — mitad Pitufina, mitad Pyrex, mitad ninguna de las dos. Una figura que escapa a las categorías conocidas y habita su propio universo con total convicción. La puerta pequeña como soporte convierte esta obra en un objeto que es pintura y escultura al mismo tiempo: tiene frente, tiene cuerpo, tiene historia. Una de las piezas más singulares de la producción reciente de De Aduriz. <strong>Certificado de autenticidad</strong> incluido.",
        "price": "Consultar",
        "dimensions": "46 x 36 cm",
        "technique": "Pastel al óleo sobre puerta de madera pequeña",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/pitufex-2025-46x36.png",
        "sold": false,
        "year": "2025"
    },
    {
        "id": "andromeda",
        "title": "Andrómedan",
        "description": "Puerta intervenida de doble cara: anverso en pastel azul eléctrico con figura cósmica andrógina coronada con el número 7; reverso en madera desnuda con cadena de palabras en tiza que mutan entre idiomas hasta terminar en Twice upon a time. <strong>Objeto único</strong>. Se ofrece a restaurar.",
        "price": "Consultar",
        "dimensions": "170 x 50 cm",
        "technique": "Pastel al óleo sobre madera",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/andromedan-2025-pastel-tiza-sobre-puerta.png",
        "images": [
            "/portfolio/sections/obras/andromedan-2025-pastel-tiza-sobre-puerta.png",
            "/portfolio/sections/obras/andromedan-2025-pastel-tiza-sobre-puerta-reverso.png"
        ],
        "sold": false,
        "year": "2025"
    },
    {
        "id": "belleza-y-felicidad-con-sol-y-luna",
        "title": "Belleza y felicidad con sol y luna",
        "description": "Una obra que celebra la dualidad: el sol y la luna conviven en un mismo espacio cargado de energía y color. <strong>Pastel tiza</strong> trabajado con una sensibilidad única que define el universo visual de Diego De Aduriz.",
        "price": "Consultar",
        "dimensions": "Consultar medidas",
        "technique": "Pastel tiza sobre papel",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/Belleza-y-felicidad-con-sol-y-luna-2014- pastel-tiz-sobre-papel.png",
        "sold": true,
        "year": "2014"
    },
    {
        "id": "diablo-elegante",
        "title": "Diablo elegante",
        "description": "<strong>100 x 70 cm</strong> de <strong>pastel tiza sobre papel</strong> (<strong>2015</strong>). El diablo elegante no es una figura amenazante — es un ser de pura presencia, casi un dandy del inframundo. <strong>Obra vendida</strong> que muestra la versatilidad del artista para trabajar con humor y profundidad.",
        "price": "Consultar",
        "dimensions": "100 x 70 cm",
        "technique": "Pastel tiza sobre papel",
        "category": "obras",
        "image": "/portfolio/sections/obras/diablo-elegante-pastel-tiza-sobre-papel-2015.jpg",
        "sold": true,
        "year": "2015"
    },
    {
        "id": "criatura-que-sopla",
        "title": "Criatura que sopla",
        "description": "Obra reciente de 2025, pintada sobre madera con pastel al óleo. Una figura enigmática que exhala vida y movimiento. <strong>Pieza única</strong> con reverso trabajado — se entrega con <strong>certificado de autenticidad</strong>.",
        "price": "Consultar",
        "dimensions": "34 x 19 cm",
        "technique": "Pastel al óleo sobre madera",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/criatura-que-sopla-pastel-al-oleo-sobre-madera-2025.png",
        "images": [
            "/portfolio/sections/obras/criatura-que-sopla-pastel-al-oleo-sobre-madera-2025.png",
            "/portfolio/sections/obras/criatura-que-sopla-pastel-al-oleo-sobre-madera-2025-back.png"
        ],
        "sold": false,
        "year": "2025"
    },
    {
        "id": "rayo-dorado",
        "title": "Rayo dorado",
        "description": "<strong>140 x 82 cm</strong> de pura energía sobre madera. La combinación de aerosol y pastel crea capas de profundidad y luz que cambian según el ángulo de visión. Una obra de gran presencia para espacios que buscan impacto visual.",
        "price": "$3000 USD",
        "dimensions": "140 x 82 cm",
        "technique": "Aerosol y pastel sobre madera",
        "category": "paisajes",
        "image": "/portfolio/sections/obras/MG_0312_1.png",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "paisaje-sol-sonriente",
        "title": "Paisaje con sol sonriente",
        "description": "Un paisaje que irradia calidez. El sol como protagonista con una expresividad propia del universo simbólico de De Aduriz. Obra en <strong>pastel sobre papel</strong>, delicada y luminosa.",
        "price": "Consultar",
        "dimensions": "80 x 60 cm",
        "technique": "Pastel sobre papel",
        "category": "paisajes",
        "image": "/portfolio/sections/obras/paisaje-con-sol-sonriente-pastel-sonre-papel.png",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "yukito",
        "title": "Yukito",
        "description": "Un gato de formato íntimo (<strong>33 x 25 cm</strong>) trabajado con <strong>pastel tiza sobre papel</strong>. Ideal para espacios pequeños o como primera obra de colección. La mirada del animal transmite una calma hipnótica.",
        "price": "$2000 USD",
        "dimensions": "33 x 25 cm",
        "technique": "Pastel tiza sobre papel",
        "category": "gatos",
        "image": "/portfolio/sections/obras/MG_0327.jpg.png",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "payaso",
        "title": "Payaso Iluminado",
        "description": "Pintado sobre una puerta de madera real (<strong>51 x 98 cm</strong>), esta obra rompe el límite entre objeto y arte. El acrílico y el pastel óleo se combinan sobre una superficie que ya tiene historia propia. Reverso intervenido — una pieza escultórica tanto como pictórica.",
        "price": "Consultar",
        "dimensions": "51 x 98 cm",
        "technique": "Acrílico y pastel óleo sobre puerta de madera",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/payaso.png",
        "images": [
            "/portfolio/sections/obras/payaso.png",
            "/portfolio/sections/obras/payaso-1-back.png"
        ],
        "sold": false,
        "year": "2025"
    },
    {
        "id": "ascension",
        "title": "Ascensión",
        "description": "Una figura que asciende, trabajada en <strong>pastel tiza sobre madera</strong>. La verticalidad de la composición refuerza el movimiento hacia arriba, hacia la luz. Una obra de gran carga simbólica y espiritual.",
        "price": "Consultar",
        "dimensions": "160 x 81 cm",
        "technique": "Pastel tiza sobre madera",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/ascension.png",
        "sold": false,
        "year": "2025"
    },
    {
        "id": "don-diego-explosion",
        "title": "Don Diego y los soles en explosión",
        "description": "Autorretrato expandido: el artista en medio de una explosión de soles, sobre tela. Una obra autobiográfica y cósmica al mismo tiempo. El <strong>pastel sobre tela</strong> logra una textura rica y vibrante que hay que ver en persona.",
        "price": "Consultar",
        "dimensions": "62 x 42 cm",
        "technique": "Pastel sobre tela",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/don-diego-y-pastel-sobre-explosion-pastel-sobre-tela.png",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "do-re-mi-fa",
        "title": "Do re mi fa sol la si",
        "description": "La música traducida en imagen. Una obra que evoca ritmo y color a partir de las notas de la escala, trabajada en <strong>pastel sobre papel</strong> con la libertad gestual característica de De Aduriz.",
        "price": "Consultar",
        "dimensions": "Consultar medidas",
        "technique": "Pastel sobre papel",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/do-re-mi-fa-sol-la-si-pastel-sobre-papel.png",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "gato-arcoiris",
        "title": "Gato arcoiris",
        "description": "<strong>100 x 65 cm</strong> de color puro. Un gato envuelto en el espectro del arcoiris, en <strong>pastel tiza sobre papel</strong>. Una de las obras más celebradas de la serie felina de De Aduriz — festiva, luminosa e imposible de ignorar.",
        "price": "Consultar",
        "dimensions": "100 x 65 cm",
        "technique": "Pastel tiza sobre papel",
        "category": "gatos",
        "image": "/portfolio/sections/obras/Diego+de+Aduriz+-+Gato+arcoiris+-+100+x+65+cm+-++pastel+sobre+papel+-+2020.png",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "gato-con-flor-de-loto",
        "title": "Gato con flor de loto",
        "description": "Un pequeño gran cuadro: <strong>25 x 18 cm</strong> donde conviven la delicadeza de la flor de loto y la presencia del gato. Formato íntimo, ideal como regalo o primera pieza de colección. <strong>Pastel tiza sobre papel</strong>, 2018.",
        "price": "Consultar",
        "dimensions": "25 x 18 cm",
        "technique": "Pastel tiza sobre papel",
        "category": "gatos",
        "image": "/portfolio/sections/obras/Diego+de+Aduriz+-+Gato+con+flor+de+loto+-+Pastel+tiza+sobre+papel+-+25+x+18+cm+-+2018.png",
        "sold": false,
        "year": "2018"
    },
    {
        "id": "cartas-a-dios",
        "title": "Cartas a Dios",
        "description": "Una obra que dialoga con lo sagrado y lo cotidiano. El título sugiere una comunicación directa, íntima, casi imposible — y sin embargo, la imagen la hace posible. Una de las piezas más personales del artista.",
        "price": "Consultar",
        "dimensions": "Consultar medidas",
        "technique": "Consultar técnica",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/cartas-a-dios.png",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "Autorretrato",
        "title": "Autorretrato",
        "description": "El artista frente a sí mismo. Trabajado en <strong>pastel tiza sobre madera</strong>, este autorretrato captura una mirada introspectiva y directa. <strong>Pieza única</strong> dentro de la serie de autorretratos de De Aduriz.",
        "price": "Consultar",
        "dimensions": "Consultar medidas",
        "technique": "Pastel tiza sobre madera",
        "category": "Autorretratos",
        "image": "/portfolio/sections/obras/autorretrato.png",
        "sold": false,
        "year": "2025"
    },
    {
        "id": "Autorretrato-2007",
        "title": "Autorretrato",
        "description": "<strong>110 x 150 cm</strong> en <strong>marcadores sobre papel</strong> — una de las obras más tempranas y sorprendentes del artista (<strong>2007</strong>). La escala y la técnica inusual hacen de esta pieza un documento histórico dentro de su obra.",
        "price": "Consultar",
        "dimensions": "110 x 150 cm",
        "technique": "Marcadores sobre papel",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/Diego+de+Aduriz+-+Autorretrato+-+110+x+150+cm+-+Marcadores+sobre+papel+-+2007.jpg",
        "sold": true,
        "year": "2007"
    },
    {
        "id": "carta-7",
        "title": "Carta 7",
        "description": "Una obra monumental: <strong>150 x 200 cm</strong> de aerosol, acrílico y <strong>pastel sobre tela</strong> (<strong>2022</strong>). La superposición de técnicas crea un campo pictórico denso y vibrante. Una de las piezas más ambiciosas y recientes de Aduriz — ideal para espacios de gran escala.",
        "price": "Consultar",
        "dimensions": "150 x 200 cm",
        "technique": "Aerosol, acrílico, pastel sobre tela",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/carta-7-aeresol, acrilico, pastel sobre tela.png",
        "sold": false,
        "year": "2022"
    },
    {
        "id": "retrato-1",
        "title": "Autorretrato con collar",
        "description": "Un autorretrato que juega con la identidad y el adorno. El collar como elemento de poder y vulnerabilidad al mismo tiempo. <strong>Pastel al óleo sobre madera</strong> con una presencia que no pasa desapercibida.",
        "price": "Consultar",
        "dimensions": "Consultar medidas",
        "technique": "Pastel al óleo sobre madera",
        "category": "Autorretratos",
        "image": "/portfolio/sections/obras/retrato-1.png",
        "sold": false,
        "year": "2025"
    },
    {
        "id": "retrato-2",
        "title": "Autorretrato con máscara de gato",
        "description": "Entre humano y animal, entre persona y personaje. El artista usa la máscara de gato para explorar otra identidad posible. Una obra cargada de humor, misterio y profundidad. <strong>Pastel al óleo sobre madera</strong>.",
        "price": "Consultar",
        "dimensions": "155 x 64 cm",
        "technique": "Pastel al óleo sobre madera",
        "category": "Autorretratos",
        "image": "/portfolio/sections/obras/retrato-2.jpeg",
        "sold": false,
        "year": "2025"
    },
    {
        "id": "the-future-is-stupid",
        "title": "The future is stupid",
        "description": "<strong>50 x 35 cm</strong> de ironía y color (<strong>2015</strong>). Una obra que envejeció muy bien — su título resuena hoy más que nunca. <strong>Técnica mixta sobre papel</strong> con la gestualidad directa de Aduriz. Para los que coleccionan arte con punto de vista.",
        "price": "$2000 USD",
        "dimensions": "50 x 35 cm",
        "technique": "Técnica mixta sobre papel",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/Diego+de+Aduriz+-+The+future+is+stupid+-+tecnica+mixta+sobre+papel+-+50+x+35+cm+-+2015.png",
        "sold": false,
        "year": "2015"
    },
    {
        "id": "abecedario",
        "title": "Abecedario",
        "description": "<strong>150 x 100 cm</strong> donde el lenguaje se vuelve imagen. Las letras del abecedario se transforman en un campo pictórico vivo, trabajado en <strong>pastel y acrílico sobre tela</strong> (<strong>2021</strong>). Una obra que habla del origen de todo: las palabras, la comunicación, el arte mismo.",
        "price": "$2500 USD",
        "dimensions": "150 x 100 cm",
        "technique": "Pastel y acrílico sobre tela",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/Diego+de+Aduriz+-+Abecedario+-+150+x+100+cm+-+Pastel+y+acrilico+sobre+tela+-+2021.png",
        "sold": false,
        "year": "2021"
    },
    {
        "id": "sin-titulo",
        "title": "Sin titulo",
        "description": "<strong>34 x 24 cm</strong> de <strong>técnica mixta sobre papel</strong> (<strong>2012</strong>). Una obra temprana que muestra la voz en formación: gestual, instintiva, sin concesiones. Para los que quieren seguir la trayectoria del artista desde sus inicios.",
        "price": "Consultar",
        "dimensions": "34 x 24 cm",
        "technique": "Técnica mixta sobre papel",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/Diego+de+Aduriz+-+Sin+titulo+-+Tecnica+mixta+sobre+papel+-+34+x+24+cm+-+2012.png",
        "sold": false,
        "year": "2012"
    },
    {
        "id": "mi-cuerpo-electrico-24",
        "title": "ULTRAVIOLETA/INFRARROJO",
        "description": "<strong>114 x 114 cm</strong> cuadrados de <strong>acrílico y aerosol sobre madera</strong> (<strong>2020</strong>). Un formato perfecto, una paleta extrema. La obra vibra entre longitudes de onda invisibles al ojo humano — pero el arte las hace visibles.",
        "price": "Consultar",
        "dimensions": "114 x 114 cm",
        "technique": "Acrílico y aerosol sobre madera",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/micuerpo.jpg",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "mi-cuerpo-electrico-29",
        "title": "Séptimo rayo",
        "description": "Una obra de gran escala (<strong>160 x 200 cm</strong>) en <strong>pastel y acrílico sobre tela</strong> (<strong>2021</strong>). El séptimo rayo como metáfora de la transformación — una energía que atraviesa y cambia todo lo que toca. Pieza central para una colección o espacio de gran envergadura.",
        "price": "Consultar",
        "dimensions": "160 x 200 cm",
        "technique": "Pastel y acrílico sobre tela",
        "category": "paisajes",
        "image": "/portfolio/sections/obras/Diego+de+Aduriz+-+Mi+cuerpo+electrico+29+160+x+200+-+Pastel+y+acrilico+sobre+tela+-+2021.jpg",
        "sold": false,
        "year": "2021"
    },
    {
        "id": "sin-titulo-3",
        "title": "Sin título",
        "description": "Una obra que habla por sí sola, sin necesitar nombre. La ausencia de título es una invitación a proyectar el significado propio. Disponible para consulta.",
        "price": "Consultar",
        "dimensions": "Consultar medidas",
        "technique": "Consultar técnica",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/sin-título.png",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-10",
        "title": "Paisaje con Flor y Hombre Plateado",
        "description": "Un paisaje de bolsillo con protagonistas insólitos: una flor y un hombre plateado que conviven en la misma escena. <strong>Técnica mixta sobre papel</strong>, pequeño formato, gran imaginación.",
        "price": "14 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "paisajes",
        "image": "/Ilustrates/dibu10.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "obra-sin-titulo",
        "title": "ESTE ES UN LUGAR SAGRADO",
        "description": "El título lo dice todo — y la imagen lo confirma. Una obra de <strong>técnica mixta</strong> que invoca la sacralidad del espacio pictórico. Para quienes buscan arte con intención y presencia.",
        "price": "Consultar",
        "dimensions": "114 x 85 cm",
        "technique": "Técnica mixta",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/IMG_0402+copia.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "obra-sin-titulo-mg-0329",
        "title": "Paisaje con duende",
        "description": "Un paisaje habitado por una presencia mágica. El duende aparece integrado a la naturaleza, como si siempre hubiera estado ahí. <strong>Pastel tiza sobre papel</strong> con la ternura y el misterio característicos de Aduriz.",
        "price": "Consultar",
        "dimensions": "40 x 30 cm",
        "technique": "Pastel tiza sobre papel",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/MG_0329.png",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "4-cabezas",
        "title": "Cuatro cabezas",
        "description": "Cuatro personalidades, cuatro miradas, un mismo plano. Una obra que multiplica la presencia y genera un diálogo silencioso entre figuras. <strong>Pastel sobre papel</strong> con composición densa y expresiva.",
        "price": "Consultar",
        "dimensions": "Consultar medidas",
        "technique": "Pastel sobre papel",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/4-cabezas-pastel-sobre-papel.png",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "paisaje-teorico",
        "title": "Paisaje teórico",
        "description": "<strong>24 x 34 cm</strong> de <strong>técnica mixta sobre papel</strong> (<strong>2009</strong>). Un paisaje que no existe en la naturaleza sino en la mente — construido con lógica propia, colores imposibles y una coherencia que solo el arte puede lograr.",
        "price": "Consultar",
        "dimensions": "24 x 34 cm",
        "technique": "Técnica mixta sobre papel",
        "category": "paisajes",
        "image": "/portfolio/sections/obras/Diego+de+Aduriz+-+Paisaje+teorico+-+Tecnica+mixta+sobre+papel+-+24+x+34+cm+-+2009.png",
        "sold": false,
        "year": "2009"
    },
    {
        "id": "paisaje-con-oso",
        "title": "Paisaje con oso",
        "description": "<strong>140 x 125 cm</strong> de <strong>aerosol y pastel sobre madera</strong>. Un oso en un paisaje que lo contiene y lo celebra — monumental como el animal, libre como la técnica. Una de las piezas más potentes del catálogo.",
        "price": "$2500 USD",
        "dimensions": "140 x 125 cm",
        "technique": "Aerosol y pastel sobre madera",
        "category": "paisajes",
        "image": "/portfolio/sections/obras/MG_0307.png",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "cuarto-creciente",
        "title": "Cuarto creciente",
        "description": "La luna en su fase de crecimiento como tema y como forma. <strong>Pastel sobre tela</strong> con una paleta nocturna y una energía expansiva. Una obra que cambia con la luz del espacio donde se instale.",
        "price": "Consultar",
        "dimensions": "52 x 31 cm",
        "technique": "Pastel sobre tela",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/cuarto-creciente-pastel-sobre-tela.png",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "gato-merlin",
        "title": "Gato Merlín",
        "description": "La obra más grande e icónica de la serie felina: <strong>205 x 210 cm</strong> de <strong>pastel sobre tela</strong>. Merlín no es un gato — es una presencia. Una obra de museo que domina cualquier espacio con autoridad y carisma. Para coleccionistas que buscan una pieza central e irrepetible.",
        "price": "$5000 USD",
        "dimensions": "205 x 210 cm",
        "technique": "Pastel sobre tela",
        "category": "gatos",
        "image": "/portfolio/sections/obras/MG_1192.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "paisaje-con-mascara-i",
        "title": "Paisaje con máscara I",
        "description": "<strong>182 x 102 cm</strong> de <strong>pintura y collage sobre tela</strong>. La máscara aparece como elemento extraño y necesario al mismo tiempo — flotando en un paisaje que la absorbe sin explicarla. Una obra que genera preguntas.",
        "price": "$3000 USD",
        "dimensions": "182 x 102 cm",
        "technique": "Pintura y collage sobre tela",
        "category": "paisajes",
        "image": "/portfolio/sections/obras/mascara2.jpg",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "gato-cosmico",
        "title": "Gato cósmico",
        "description": "<strong>80 x 110 cm</strong> de <strong>pastel tiza</strong> (<strong>2013</strong>). Un gato que trasciende lo terrestre y ocupa el cosmos como si le perteneciera. <strong>Obra vendida</strong> — si te interesa una pieza similar, escribinos.",
        "price": "Consultar",
        "dimensions": "80 x 110 cm",
        "technique": "Pastel tiza",
        "category": "gatos",
        "image": "/portfolio/sections/obras/Diego+de+Aduriz+-+Gato+cosmico+-+Pastel+tiza+-+80+x+110+cm+2013.jpeg",
        "sold": true,
        "year": "2013"
    },
    {
        "id": "paisaje-con-mascara-ii",
        "title": "Paisaje con máscara II",
        "description": "La segunda entrega de la serie de máscaras en paisajes. <strong>Pintura y collage sobre tela</strong> — la máscara como segundo rostro del territorio. Una obra que dialoga con la primera y puede exhibirse junto a ella.",
        "price": "Consultar",
        "dimensions": "182 x 102 cm",
        "technique": "Pintura y collage sobre tela",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/mascara1.jpg",
        "sold": false,
        "year": "2020"
    },
    {
        "id": "paisaje-azul-collage",
        "title": "Paisaje azul",
        "description": "Collage de atmósfera serena y profunda. El azul domina y unifica una composición construida con fragmentos que juntos forman un territorio propio. Una obra contemplativa para espacios que buscan calma.",
        "price": "Consultar",
        "dimensions": "Consultar medidas",
        "technique": "Collage",
        "category": "paisajes",
        "image": "/portfolio/sections/obras/paisaje-azul-collage.png",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "paisaje-con-monstruo-amistoso",
        "title": "Paisaje con monstruo amistoso",
        "description": "<strong>24 x 34 cm</strong> de <strong>lápiz sobre papel</strong> (<strong>2011</strong>). El monstruo aquí no da miedo — es parte del paisaje, casi un vecino. Una obra tierna y precisa que muestra el universo de Aduriz desde sus fundamentos gráficos.",
        "price": "Consultar",
        "dimensions": "24 x 34 cm",
        "technique": "Lápiz sobre papel",
        "category": "paisajes",
        "image": "/portfolio/sections/obras/Diego+de+Aduriz+-+Piasaje+con+monstruo+amistoso+-+Lapiz+sobre+papel+-+24+x+34+cm+-+2011.jpeg",
        "sold": false,
        "year": "2011"
    },
    {
        "id": "luz-azul",
        "title": "LUZAZUL",
        "description": "<strong>180 x 210 cm</strong> de acrílico y <strong>pastel tiza</strong> sobre tela (<strong>2015</strong>). Una obra que llena una habitación de luz azul — una presencia física, casi meteorológica. De las obras más importantes y de mayor escala del artista.",
        "price": "Consultar",
        "dimensions": "180 x 210 cm",
        "technique": "Acrílico y pastel tiza sobre tela",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/luz_azul.jpg",
        "sold": false,
        "year": "2015"
    },
    {
        "id": "gato-celeste",
        "title": "Gato celeste",
        "description": "<strong>35 x 25 cm</strong> de <strong>pastel tiza sobre papel</strong> — pequeño, intenso, celestial. El gato celeste flota entre el cielo y la tierra con una gracia que solo el pastel puede capturar así. Ideal como primera obra o regalo para amantes del arte y los gatos.",
        "price": "$1500 USD",
        "dimensions": "35 x 25 cm",
        "technique": "Pastel tiza sobre papel",
        "category": "gatos",
        "image": "/portfolio/sections/obras/MG_0327.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "puerta-azul",
        "title": "Puerta Azul",
        "description": "<strong>210 x 92 cm</strong> de pintura y <strong>pastel tiza sobre madera</strong> (<strong>2015–2017</strong>). Una puerta real convertida en umbral simbólico — azul como el cielo, como el agua, como lo que está del otro lado. <strong>Obra vendida</strong> que dejó huella.",
        "price": "Consultar",
        "dimensions": "210 x 92 cm",
        "technique": "Pintura y pastel tiza sobre madera",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/Diego+de+Aduriz+-+Puerta+Azul+-+210+x+92+cm+-+Pintura+y+pastel+tiza+sobre+madera+-+2015_2017.jpeg",
        "sold": true,
        "year": "2015"
    },
    {
        "id": "puerta-1",
        "title": "Espíritu (Humito)",
        "description": "<strong>80 x 195 cm</strong> de <strong>acrílico y pastel óleo sobre puerta de madera</strong> (<strong>2018</strong>). El espíritu emerge como humito — liviano, efímero, irresistible. El soporte puerta le da una dimensión corporal única: esta obra tiene la escala de una persona.",
        "price": "Consultar",
        "dimensions": "80 x 195 cm",
        "technique": "Acrílico y pastel óleo sobre puerta / Técnica mixta sobre madera",
        "category": "pasteles",
        "image": "/portfolio/sections/obras/puerta-1-espiritu(humite)-tecnica-pastel-sobre-puerta-tecnoca-mixta-sobre-madera.png",
        "images": [
            "/portfolio/sections/obras/puerta-1-espiritu(humite)-tecnica-pastel-sobre-puerta-tecnoca-mixta-sobre-madera.png",
            "/portfolio/sections/obras/puerta-1-back.png"
        ],
        "sold": false,
        "year": "2018"
    },
    {
        "id": "dibu-1",
        "title": "Diábolo",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. Pequeño formato coleccionable, firmado por el artista. Ideal para iniciar una colección accesible.",
        "price": "12 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu1.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-2",
        "title": "Ilustración #2",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada. Una forma accesible de tener una obra original de Diego De Aduriz.",
        "price": "22 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu2.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-3",
        "title": "Ilustración #3",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong> y firmada — arte original a precio de entrada.",
        "price": "8 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu3.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-4",
        "title": "Ilustración #4",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada por el artista.",
        "price": "15 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu4.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-5",
        "title": "Ilustración #5",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada por el artista.",
        "price": "19 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu5.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-6",
        "title": "Ilustración #6",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada por el artista.",
        "price": "6 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu6.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-7",
        "title": "Ilustración #7",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada por el artista.",
        "price": "24 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu7.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-8",
        "title": "Ilustración #8",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada por el artista.",
        "price": "11 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu8.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-9",
        "title": "Ilustración #9",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada por el artista.",
        "price": "20 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu9.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-11",
        "title": "Diábolo 1",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada por el artista.",
        "price": "9 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu11.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-12",
        "title": "Paisaje fenomenal",
        "description": "Un paisaje que merece su nombre. Ilustración original en <strong>técnica mixta sobre papel</strong> — pequeño formato, gran universo.",
        "price": "25 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu12.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-14",
        "title": "Diábolo 4",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada por el artista.",
        "price": "7 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu14.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-15",
        "title": "Diábolo 5",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada por el artista.",
        "price": "18 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu15.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-16",
        "title": "Diábolo 6",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada por el artista.",
        "price": "23 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu16.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-19",
        "title": "Diábolo 9",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada por el artista.",
        "price": "16 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu19.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "dibu-20",
        "title": "Ilustración #20",
        "description": "Ilustración original en <strong>técnica mixta sobre papel</strong>. <strong>Pieza única</strong>, firmada por el artista.",
        "price": "13 USD",
        "dimensions": "Consultar medidas",
        "technique": "Técnica mixta sobre papel",
        "category": "ilustraciones",
        "image": "/Ilustrates/dibu20.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "digital-artwork-1",
        "title": "Digital Artwork #1",
        "description": "Obra digital original. Impresión de alta calidad disponible en <strong>30 x 40 cm</strong>. El arte digital de Aduriz trae su universo visual a un formato reproducible y accesible.",
        "price": "$20.00 USD",
        "dimensions": "30 x 40 cm",
        "technique": "Arte digital",
        "category": "digital",
        "image": "https://64.media.tumblr.com/c29b535685cd870a467bdc6eb0d60ef2/tumblr_n27f1t2IvP1r74tb2o1_1280.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "digital-artwork-2",
        "title": "Digital Artwork #2",
        "description": "Obra digital original. Impresión de alta calidad disponible en <strong>30 x 40 cm</strong>.",
        "price": "$20.00 USD",
        "dimensions": "30 x 40 cm",
        "technique": "Arte digital",
        "category": "digital",
        "image": "https://64.media.tumblr.com/c3123779be189a5a8737b190f595574a/tumblr_n275dsU7Xr1r74tb2o1_250.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "digital-artwork-3",
        "title": "Digital Artwork #3",
        "description": "Obra digital original. Impresión de alta calidad disponible en <strong>30 x 40 cm</strong>.",
        "price": "$20.00 USD",
        "dimensions": "30 x 40 cm",
        "technique": "Arte digital",
        "category": "digital",
        "image": "https://64.media.tumblr.com/9e5c31eb51ce7e28c7982f271746f302/tumblr_n275eaKQwf1r74tb2o1_640.jpg",
        "sold": false,
        "year": "Consultar año"
    },
    {
        "id": "digital-artwork-4",
        "title": "Digital Artwork #4",
        "description": "Obra digital original. Impresión de alta calidad disponible en <strong>30 x 40 cm</strong>.",
        "price": "$20.00 USD",
        "dimensions": "30 x 40 cm",
        "technique": "Arte digital",
        "category": "digital",
        "image": "https://64.media.tumblr.com/15528b2c6461bb6795b432f0b5a67bd3/tumblr_n2757yIlWR1r74tb2o1_540.jpg",
        "sold": false,
        "year": "Consultar año"
    }
];

/**
 * Carousel sections configuration.
 * Each section references products by their image path.
 * This is the single source of truth for which products
 * appear in each carousel on the shop landing page.
 */
window.carouselSections = [
    {
        id: "destacados",
        labelKey: "hero.featured",
        labelDefault: "Destacados",
        images: [
            "/portfolio/sections/obras/MG_0307.png",
            "/portfolio/sections/obras/MG_0312_1.png",
            "/portfolio/sections/obras/MG_0327.jpg.png",
            "/portfolio/sections/obras/MG_1192.jpg"
        ]
    },
    {
        id: "novedades",
        labelKey: "shop.novedades",
        labelDefault: "Novedades",
        dynamic: "newest",
        images: []
    },
    {
        id: "gatos",
        labelKey: null,
        labelDefault: "Gatos",
        images: [
            "/portfolio/sections/obras/MG_0327.jpg.png",
            "/portfolio/sections/obras/MG_0327.jpg",
            "/portfolio/sections/obras/MG_1192.jpg",
            "/portfolio/sections/obras/micuerpo.jpg",
            "/portfolio/sections/obras/Diego+de+Aduriz+-+Gato+arcoiris+-+100+x+65+cm+-++pastel+sobre+papel+-+2020.png",
            "/portfolio/sections/obras/Diego+de+Aduriz+-+Gato+con+flor+de+loto+-+Pastel+tiza+sobre+papel+-+25+x+18+cm+-+2018.png",
            "/portfolio/sections/obras/Diego+de+Aduriz+-+Gato+cosmico+-+Pastel+tiza+-+80+x+110+cm+2013.jpeg"
        ]
    },
    {
        id: "autorretratos",
        labelKey: null,
        labelDefault: "Autorretratos",
        images: [
            "/portfolio/sections/obras/autorretrato.png",
            "/portfolio/sections/obras/retrato-1.png",
            "/portfolio/sections/obras/retrato-2.jpeg"
        ]
    },
    {
        id: "paisajes",
        labelKey: null,
        labelDefault: "Paisajes",
        images: [
            "/portfolio/sections/obras/MG_0307.png",
            "/portfolio/sections/obras/MG_0312_1.png",
            "/portfolio/sections/obras/mascara2.jpg",
            "/portfolio/sections/obras/Diego+de+Aduriz+-+Mi+cuerpo+electrico+29+160+x+200+-+Pastel+y+acrilico+sobre+tela+-+2021.jpg",
            "/portfolio/sections/obras/Diego+de+Aduriz+-+Piasaje+con+monstruo+amistoso+-+Lapiz+sobre+papel+-+24+x+34+cm+-+2011.jpeg",
            "/portfolio/sections/obras/Diego+de+Aduriz+-+Paisaje+teorico+-+Tecnica+mixta+sobre+papel+-+24+x+34+cm+-+2009.png"
        ]
    }
];